### ISSUE TITLE
Client not existing?

### ISSUE THREAD

**Issue by Carbsta** [soundcloud/soundcloud-python#72]
I'm using python 3.5 (which could be the problem) and when I try and create an instance of the Client class, passing in my client_id it returns this attribute error:

```
Traceback (most recent call last):
  File "soundcloud.py", line 1, in <module>
    import soundcloud
  File "/home/tom/Soundbot/soundcloud.py", line 3, in <module>
    client = soundcloud.Client(client_id="myClientID")
AttributeError: module 'soundcloud' has no attribute 'Client'
```

Is the documentation not up to date and there is a new way of making a client? Or is the library broken or is it python 3.5 causing the issue?

I installed the soundcloud library using pip.

**Comment by ata4** [comment]
Don't name your script file "soundcloud.py", since it collides with the module "soundcloud".

**Comment by solancer** [comment]
I have the same issue and I've not named my script soundcloud.py
