### ISSUE TITLE
Registering a new app on soundcloud is unavailable.

### ISSUE THREAD

**Issue by Gabrieldaboss65** [soundcloud/soundcloud-python#85]
I'm working on a bot and i need it to have the ability to get the url to a song on soundcloud. To use this thought i need the soundcloud api and an app registered to it. It says that signing up a new app is offline and its been like that for a while. any new on how this will be fixed and whats going to be done? Apparently it's been like this for a while.

**Comment by saulojoab** [comment]
Still unavailable. Really sad, I really wanted to use it as well.

**Comment by saulojoab** [comment]
Just a little update from the official [Soundcloud Support Twitter](https://twitter.com/SCsupport/status/1117797063608229888):

![image](https://user-images.githubusercontent.com/37988252/56340358-135fc200-6188-11e9-8aa0-575f2e2b5268.png)

I guess that's it, folks.

**Comment by Gabrieldaboss65** [comment]
well thats bullshit. might as well delete the developers tab and the github repos

**Comment by saulojoab** [comment]
That's exactly what I told them, lol
![image](https://user-images.githubusercontent.com/37988252/56444102-b837e780-62cd-11e9-9a43-9e77e4f136e3.png)

**Comment by AmirBraham** [comment]
Any updates on this ? is there any workaround ?

**Comment by Gabrieldaboss65** [comment]
reverse their api unnofficialy from scrach (deffinitly violates tos). then again i do believe that previously made api keys are still active.
