### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by Directory** [soundcloud/soundcloud-python#86]
Read my issue #85 . Soundcloud developer api is dead. this repo is useless. all developer tools are useless. theres no reason to keep them open and active when the targetted api is dead. The repo needs to be archived at this point.

**Comment by jamesacampbell** [comment]
People with client ids and client secrets can still use the code, so I vote to not shut this down. New sign-ups to create new apps using soundcloud's API is closed on their developer portal, this is different than it being shutdown completely.
